application: nittygrittyrev
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon.ico
  static_files: img/favicon.ico
  upload: img/favicon.ico
- url: /js
  static_dir: js
- url: /css
  static_dir: css
- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest